// Generated by Finicky Kickstart 
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Firefox",      
  handlers: [
    {
      match: /^https?:\/\/.*\.google\.com\/.*$/,
      browser: "Brave Browser"
    }
  ]
}
